config/routes.rb
Rails.application.routes.draw do
  get '/v1/users/:id/billing' => 'subscriptions#index', as: :billing
  patch '/v1/users/:id/billing' => 'subscriptions#edit_subscription', as: :edit_subscription
  get '/v1/users/:id/billing/history' => 'subscriptions#billing_history', as: :billing_history
  get '/v1/subscriptions/new' =>'subscriptions#new', as: :new_subscription
  delete '/v1/users/:id/billing' => 'subscriptions#destroy', as: :subscription
  get '/v1/users/:id/billing/sub_data' => 'subscriptions#subscription_data', as: :sub_data

  get '/v1/users/:id/billing/invoices' => 'invoices#index', as: :invoices
  get '/v1/users/:id/billing/invoices/:invoice_id' => 'invoices#show', as: :invoice_show
  get '/v1/users/:id/billing/invoices/:invoice_id/pdf' => 'invoices#create_pdf', as: :create_invoice_pdf
  get '/v1/users/:id/billing/invoices/:invoice_id/send' => 'invoices#send_customer_invoice_email', as: :send_invoic_email
  get '/v1/users/:id/billing/invoices/:custom_id/custom' => 'invoices#custom_user_invoices', as: :custom_show

  delete '/v1/users/:id/billing/add-ons/:add_ons_id' => 'subscriptions#delete_add_ons', as: :delete_add_ons

  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v1/payments' => 'payments#new', as: :new_checkout
  post '/v1/payments' => 'payments#create', as: :new_charge
  post '/v1/users/:id/billing/plans/change' => 'payments#upgrade_downgrade_plan'

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v1/cameras'), as: :root
  get '/v1/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras/new' => 'cameras#new', as: :cameras_new
  get '/v1/cameras/new-test' => 'cameras#addcam_test', as: :cameras_new_test
  post '/v1/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v1/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v1/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v1/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v1/cameras/:id/clip/:clip_id/play' => 'pages#play', as: :play_clip
  get '/v1/cameras/:id/share/request' => 'pages#revoke_request'
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v1/cameras/:id/*subpath' => 'cameras#single'
  get '/v1/users/:id/billing/*subpath' => 'subscriptions#index'

  get '/v1/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v1/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v1/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v1/users/signup' => 'users#new', as: :signup
  post '/v1/users/signup' => 'users#create'
  get '/v1/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v1/users/password-reset' => 'users#password_reset_request'
  get '/v1/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v1/users/password-new' => 'users#password_update'
  get '/v1/users/:id/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/confirm' => 'users#confirm'
  get '/v1/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  delete '/v1/users/signout' => 'sessions#destroy', as: :signout
  get '/v1/users/:id' => 'users#user_account', as: :user_account
  get '/v1/users/:id/password' => 'users#password_change', as: :password_change
  get '/v1/users/:id/settings' => 'users#settings', as: :user_settings
  delete '/v1/users/:id' => 'users#delete'
  post '/v1/users/:id' => 'users#settings_update'
  put '/v1/users/:id/password/change' => 'users#change_password', as: :user_change_password

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'
  get '/widget' => 'widgets#widget', as: :widget

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  post '/share' => 'sharing#create'
  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :owns_data!
  before_action :get_camares
  layout "user-account"
  include SessionsHelper
  include ApplicationHelper
  include StripeCustomersHelper
  include StripeInvoicesHelper
  require "stripe"
  require "date"
  require "open-uri"

  def index
    @invoices = retrieve_customer_invoices
  end

  def show
    if params[:invoice_id]
      @subscription = current_subscription
      @invoice = retrieve_customer_invoice(params[:invoice_id])
      @invoice_lines = retrieve_customer_invoice_lines(params[:invoice_id])
      if !@invoice || !@invoice_lines
        redirect_to billing_path(current_user.username)
      end
    else
      redirect_to billing_path(current_user.username)
    end
  end

  def custom_user_invoices
    custom_id = params[:custom_id]
    if current_user.insight_id.present? && custom_id.present?
      custom_url =  "#{ENV['DOCUMENT_URL']}AuthKey=#{ENV['document_auth_key']}&JSONObject&DocNumber=#{custom_id}"
      product_url = "#{ENV['PRODUCT_URL']}AuthKey=#{ENV['product_auth_key']}&JSONObject&DocNumber=#{custom_id}"
      response_custom = open(custom_url).read
      response_product = open(product_url).read
      resp_custom = JSON.parse(response_custom)
      resp_product = JSON.parse(response_product)
      res_custom = resp_custom['result']
      res_product = resp_product['result']
      @custom = res_custom[0]
      @product = res_product
    else
      redirect_to billing_path(current_user.username)
    end
  rescue => error
    Rails.logger.error "Exception caught while accessing insight url.\nCause: #{error}\n" + error.backtrace.join("\n")
    flash[:message] = "An error occurred while accessing insight url. "\
                      "Please try again and, if this problem persists, contact "\
                      "support."
    redirect_to billing_path(current_user.username)
  end

  def send_customer_invoice_email
    begin
      if params[:invoice_id]
        subscription = current_subscription
        period = subscription.interval
        invoice = retrieve_customer_invoice(params[:invoice_id])
        invoice_lines = retrieve_customer_invoice_lines(params[:invoice_id])
        if !invoice || !invoice_lines
          flash[:message] = "Unable to locate your invoice details in the system. Please refresh your view and try again."
        else
          StripeMailer.send_customer_invoice(invoice, invoice_lines, period, current_user.email).deliver_now
          flash[:message] = 'We’ve sent you an invoice email.'
        end
      else
        flash[:message] = "Unable to locate your invoice details in the system. Please refresh your view and try again."
      end
    rescue
      flash[:message] = "Unable to locate your invoice details in the system. Please refresh your view and try again."
    end
    redirect_to billing_path(current_user.username)
  end

  def create_pdf
    begin
      @subscription = current_subscription
      @invoice = retrieve_customer_invoice(params[:invoice_id])
      @invoice_lines = retrieve_customer_invoice_lines(params[:invoice_id])
      @html = render_to_string(:action => :create_pdf, :layout => "mailer.html.erb")
      pdf = WickedPdf.new.pdf_from_string(@html)
      send_data(pdf,
        :filename    => "#{@invoice[:id]}.pdf",
        :disposition => "attachment")
    rescue => _error
      flash[:message] = "Exception caught in create invoice pdf, Cause: #{_error.message}"
      redirect_to billing_path(current_user.username)
    end
  end

  def get_camares
    @cameras = load_user_cameras(true, false)
  end
end

app/views/invoices/create_pdf.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;">
<head>
  <title>Evercam.io</title>
</head>
<body bgcolor="#FFFFFF" style="font-family: Arial, Helvetica, sans-serif; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; margin: 0; padding: 0;">
<style type="text/css">
  div[class="column"] {
    width: auto !important; float: none !important;
  }
  table.social div[class="column"] {
    width: auto !important;
  }
  table {
    border-collapse: collapse;
    width:100%;
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
    padding: 0;
  }
  .table-product tr{
      border-bottom: 1px solid #aaaaaa;
  }
  h3 {
    margin-bottom: 3px;
  }
</style>
<!-- HEADER -->
<table class="head-wrap" bgcolor="#f5f5f5" style="width: 100%; margin: 0; padding: 0;">
  <tr style="margin: 0; padding: 0;">
    <td style="margin: 0; padding: 0;"></td>
    <td class="header container" style="display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">
      <div class="content" style="max-width: 600px; display: block; margin: 0 auto; padding: 15px;">
        <table bgcolor="#f5f5f5" style="width: 100%; margin: 0; padding: 0;">
          <tr style="margin: 0; padding: 0;text-align:center;">
            <td style="margin: 0; padding: 0;">
              <img src="http://www.evercam.io/img/logo.png" class="logo" style="max-width:28%;max-width:175px;padding-top:10px;margin:0;">
            </td>
          </tr>
        </table>
      </div>
    </td>
    <td style="margin: 0; padding: 0;"></td>
  </tr>
</table>
<!-- /HEADER -->
<!-- BODY -->
<table class="body-wrap" style="font-family: Arial, Helvetica, sans-serif; width: 100%; margin: 0; background-color:#f5f5f5; padding: 0;">
  <tr style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;"><td style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;"></td>
    <td class="container" bgcolor="#FFFFFF" style="font-family: Arial, Helvetica, sans-serif; display: block !important; border-radius:3px; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">

      <div class="content" style="font-family: Arial, Helvetica, sans-serif;font-weight: normal; font-size: 14px; max-width: 600px; display: block; margin: 0 auto; padding: 15px;">
        <table>
          <tr style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;">
            <td colspan="3" style="margin: 0; padding: 0;">
              <div style="text-align: right">
                <h3>INVOICES</h3>
                <div style="color: green;"><%= @invoice[:paid] ? "Paid" : "Pending" %></div>
                <div style="margin-bottom: 5px;margin-top: 15px;"><strong>Invoice ID:</strong> <%= @invoice[:id] %></div>
                <div style="margin-bottom: 5px;"><strong>Date:</strong> <%= Time.at(@invoice[:date]).strftime("%B %d, %Y") %></div>
                <div style="margin-bottom: 5px;"><strong>Period:</strong> <%= Time.at(@invoice[:date]).strftime("%B %d, %Y") %> <span style="color:grey;">to</span> <%= @subscription.interval.eql?("year") ? (Time.at(@invoice[:date]) + 1.year).strftime("%B %d, %Y") : (Time.at(@invoice[:date]) + 30.days).strftime("%B %d, %Y") %></div>
              </div>
            </td>
          </tr>
          <tr>
            <td style="width: 45%;" valign="top">
              <div style="margin-top: 30px;">
                <div style="padding: 2px 0px;"><strong>From:</strong> Evercam.io</div>
                <div style="padding: 3px 0px;">Wayra Ireland</div>
                <div style="padding: 3px 0px;">29 Sir John Rogerson's Quay</div>
                <div style="padding: 3px 0px;">Dublin, Ireland</div>
              </div>
            </td>
            <td style="width: 10%;"></td>
            <td style="width: 45%;" valign="top">
              <div style="margin-top: 30px;text-align: right;">
                <div style="padding: 2px 0px;"><strong>To:</strong> <%= current_user.email -%></div>
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <div style="margin-top: 30px;">
                <table class="table-product">
                  <tr>
                    <th align="left">Product</th>
                    <th align="center">Qty.</th>
                    <th align="right">Price</th>
                  </tr>
                  <% @invoice_lines.each do |item| %>
                    <tr style="border-top: solid 1px #eeeeee;">
                      <td align="left"><%= item.description.blank? ? item.plan.id : item.description%></td>
                      <td align="center"><%= item.quantity %></td>
                      <td align="right"><%= item.amount < 0 ? "-" : "" %>&euro;<%= number_with_precision(item.amount.abs / 100, :precision => 2) %> </td>
                    </tr>
                  <% end %>
                </table>
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="3">
              <div style="margin-top: 30px;font-weight: bold">
                <div>
                  <div style="float: right;width:100px;text-align: right;"><%= @invoice[:subtotal] < 0 ? "-" : "" %>&euro;<%= number_with_precision(@invoice[:subtotal].abs / 100, :precision => 2) %></div>
                  <div style="float: right;width:100px;text-align: right;">Sub Total:</div>
                </div>
                <div style="clear: both;"></div>
                <div>
                  <div style="float: right;width:100px;text-align: right;"><%= @invoice[:total] < 0 ? "-" : "" %>&euro;<%= number_with_precision(@invoice[:total].abs / 100, :precision => 2) %></div>
                  <div style="float: right;width:100px;text-align: right;">Total:</div>
                </div>
              </div>
            </td>
          </tr>
        </table>
      </div>
    </td>
    <td style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;"></td>
  </tr>
</table>
<!-- /BODY -->
<!-- FOOTER -->
<table class="footer-wrap" style="background-color:#f5f5f5; font-family: Arial, Helvetica, sans-serif; width: 100%; clear: both !important; margin: 0; padding: 0;">
  <tr style="margin: 0; padding: 0;"><td style="font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0;"></td>
    <td class="container" style="text-align:center; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0;">

      <p style="color:#aaaaaa; font-family: Arial, Helvetica, sans-serif; font-weight: normal; font-size: 12px; line-height: 1.0; margin: 10px 0 40px; padding: 0;">&copy; 2015    <a href="http://www.evercam.io" style="color:#428bca;text-decoration: none;">www.evercam.io</a></p>

    </td>
  </tr>
</table>
<!-- /FOOTER -->
</body>
</html>

app/views/invoices/custom_user_invoices.html.erb
<div class="subscriptions page-content-wrapper">
  <div class="page-content">
    <div class="portlet-body">
      <div class="invoice col-md-12">
        <div class="card">
          <img class="img-invoice" src="/assets/evercam-invoice.png">
          <div class="col-md-12">
            <% @address = @custom['CUSTOMERTEXT'].split("\n") %>
            <div class="col-md-4 address ">
              <% @address.each do |address| %>
                <div class="address-text"><%= address  %></div>
              <%end%>
            </div>

            <div class="invoice-header col-md-8 text-right">
              <div class="head-text"><strong class="margin-right-10" >Reference:</strong> <%= @custom['REFERENCE']? @custom['REFERENCE'] : "None"  %></div>
              <div class="head-text"><strong class="margin-right-10" >Account No:</strong> <%= @custom['CUSTOMERCODE'] %></div>
              <div class="head-text"><strong class="margin-right-10" >Manager:</strong> <%= @custom['MANAGERNAME'] %></div>
              <div class="head-text"><strong class="margin-right-10">Invoice Date:</strong> <%= @custom['POSTDATE'] %></div>
              <div class="head-text"><strong class="margin-right-10">Terms:</strong>As per quotation</div>
            </div>
          </div>

          <div class="col-md-12 margin-top-30">
            <div class="invoice-no"><strong>Invoice No. </strong><strong><%= @custom['NUMBER'] %></strong></div>

          </div>

          <div class="col-md-12 ">
            <table class="table">
              <tr>
                <th class="col-md-7">
                  Product or Service
                </th>
                <th class="col-md-1 text-right">
                  Quantity
                </th>
                <th class="col-md-1 text-right">
                  Price €
                </th>
                <th class="col-md-1 text-right">
                  VAT Exc €
                </th>
                <th class="col-md-1 text-right">
                  VAT €
                </th>
                <th class="col-md-1 text-right">
                  VAT Inc €
                </th>

              </tr>
              <% @product.each do |products| %>
              <tr>
                <td class="col-md-7"><%= products['ITEMNAME'] %></td>
                <td class="col-md-1 text-right"><%= products['QUANTITY'] %></td>
                <td class="col-md-1 text-right"><%= products['FRGSALEPRICE'] %></td>
                <td class="col-md-1 text-right"><%= products['FRGAMOUNTVATEXC'] %></td>
                <td class="col-md-1 text-right"><%= products['FRGVATAMOUNT'] %></td>
                <td class="col-md-1 text-right"><%= products['FRGAMOUNTVATINC'] %> </td>
              </tr>
              <% end %>
            </table>
          </div>
          <div class="col-md-12 text-right footer-text pull-right">
            <div class="row">
              <div class="col-md-9">Total:</div>
              <%@exc = 0 %>
              <%@vat = 0 %>
              <%@inc = 0 %>
              <% @product.each do |products| %>
                <%@exc = @exc + products['FRGAMOUNTVATEXC'].to_f %>
                <%@vat = @vat + products['FRGVATAMOUNT'].to_f %>
                <%@inc = @inc + products['FRGAMOUNTVATINC'].to_f %>
              <%end%>
              <div class="col-md-1 text-right"><%= @exc.round(2) %> €</div>
              <div class="col-md-1 text-right"><%= @vat.round(2) %> €</div>
              <div class="col-md-1 text-right"><%= @inc.round(2) %> €</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<div class="bb-alert alert alert-info" style="display:none;">
  <span></span>
</div>
<div class="subscriptions invoices page-content-wrapper">
  <div class="page-content">
    <div class="portlet-body">
      <div class="col-md-12 margin-top-20">
        <div class="card">
        <% if !@invoices %>
          <p>You have no invoices.</p>
        <% else %>
          <table style="width:100%;" class="table table-full-width">
            <tr>
              <th class="col-md-2">Date</th>
              <th class="col-md-2">Total</th>
              <th class="col-md-2">Status</th>
              <th class="col-md-2">Action</th>
            </tr>
            <% @invoices.each do |invoice| %>
              <tr>
                <td><%= link_to Time.at(invoice[:date]).strftime("%d %B %Y"), invoice_show_path(current_user.username, invoice[:id])%></td>
                <td><%= cents_to_currency(invoice[:total]) %></td>
                <td>
                  <% if invoice[:paid] %>
                    <span class="green">Paid</span>
                  <% else %>
                    <span class='green'>Pending</span>
                  <% end %>
                </td>
                <td>
                  <span class="download-pdf"><%= link_to "PDF", create_invoice_pdf_path(current_user.username, invoice[:id])%><i class="fa fa-file-pdf-o"></i></span>
                  <span class="send-email"><%= link_to "Email", send_invoic_email_path(current_user.username, invoice[:id])%><i class="fa fa-send-o"></i></span>
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
    Notification.init(".bb-alert")
    <% if flash[:message] %>
    Notification.show('<%= flash[:message] %>');
    <% end %>
  });
</script>

app/views/invoices/show.html.erb
<div class="subscriptions page-content-wrapper">
  <div class="page-content">
    <div class="portlet-body">
      <div class="invoice col-md-12">
        <div class="card">
          <div class="col-md-12">

            <div class="invoice-header text-right">
              <h3 class="invoice-title">Invoice</h3>
              <div class="invoice-status"><%= @invoice[:paid] ? "Paid" : "Pending" %></div>
              <div class="head-text"><strong>Invoice ID:</strong> <%= @invoice[:id] %></div>
              <div class="head-text"><strong>Date:</strong> <%= Time.at(@invoice[:date]).strftime("%B %d, %Y") %></div>
              <% if @subscription %>
                <div class="head-text"><strong>Period:</strong> <%= Time.at(@invoice[:date]).strftime("%B %d, %Y") %> <span class="grey">to</span> <%= @subscription.interval.eql?("year") ? (Time.at(@invoice[:date]) + 1.year).strftime("%B %d, %Y") : (Time.at(@invoice[:date]) + 30.days).strftime("%B %d, %Y") %></div>
              <% end %>
            </div>
          </div>

          <div class="col-md-12 margin-top-30">
            <div class="col-md-4 address">
              <div class="address-title"><strong>From:</strong> Evercam.io</div>
              <div class="address-text">Wayra Ireland</div>
              <div class="address-text">29 Sir John Rogerson's Quay</div>
              <div class="address-text">Dublin, Ireland</div>
            </div>

            <div class="col-md-4 pull-right address text-right">
              <div class="address-title"><strong>To:</strong> <%= current_user.email -%></div>
              <div class="address-text">
                  </div>
            </div>
          </div>

          <div class="col-md-12 margin-top-30">
            <table class="table">
              <tr>
                <th class="col-md-2">
                  Product
                </th>
                <th class="col-md-2">
                  Qty.
                </th>
                <th class="col-md-2 text-right">
                  Price
                </th>

              </tr>
              <% @invoice_lines.each do |item| %>
                <tr>
                  <td class="col-md-4"><%= item.description.blank? ? item.plan.id : item.description%></td>
                  <td class="col-md-2"><%= item.quantity %></td>
                  <td class="col-md-2 text-right"><%= cents_to_currency item.amount %> </td>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="col-md-12 text-right footer-text pull-right">
            <div class="row invoice-total">
              <div class="col-md-10">Sub Total:</div>
              <div class="col-md-2"><%= cents_to_currency(@invoice[:subtotal]) %></div>
            </div>
            <div class="row">
              <div class="col-md-10">Total:</div>
              <div class="col-md-2"><%= cents_to_currency(@invoice[:total]) %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>