config/routes.rb
Rails.application.routes.draw do
  get '/v1/users/:id/billing' => 'subscriptions#index', as: :billing
  patch '/v1/users/:id/billing' => 'subscriptions#edit_subscription', as: :edit_subscription
  get '/v1/users/:id/billing/history' => 'subscriptions#billing_history', as: :billing_history
  get '/v1/subscriptions/new' =>'subscriptions#new', as: :new_subscription
  delete '/v1/users/:id/billing' => 'subscriptions#destroy', as: :subscription
  get '/v1/users/:id/billing/sub_data' => 'subscriptions#subscription_data', as: :sub_data

  get '/v1/users/:id/billing/invoices' => 'invoices#index', as: :invoices
  get '/v1/users/:id/billing/invoices/:invoice_id' => 'invoices#show', as: :invoice_show
  get '/v1/users/:id/billing/invoices/:invoice_id/pdf' => 'invoices#create_pdf', as: :create_invoice_pdf
  get '/v1/users/:id/billing/invoices/:invoice_id/send' => 'invoices#send_customer_invoice_email', as: :send_invoic_email
  get '/v1/users/:id/billing/invoices/:custom_id/custom' => 'invoices#custom_user_invoices', as: :custom_show

  delete '/v1/users/:id/billing/add-ons/:add_ons_id' => 'subscriptions#delete_add_ons', as: :delete_add_ons

  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v1/payments' => 'payments#new', as: :new_checkout
  post '/v1/payments' => 'payments#create', as: :new_charge
  post '/v1/users/:id/billing/plans/change' => 'payments#upgrade_downgrade_plan'

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v1/cameras'), as: :root
  get '/v1/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras/new' => 'cameras#new', as: :cameras_new
  get '/v1/cameras/new-test' => 'cameras#addcam_test', as: :cameras_new_test
  post '/v1/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v1/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v1/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v1/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v1/cameras/:id/clip/:clip_id/play' => 'pages#play', as: :play_clip
  get '/v1/cameras/:id/share/request' => 'pages#revoke_request'
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v1/cameras/:id/*subpath' => 'cameras#single'
  get '/v1/users/:id/billing/*subpath' => 'subscriptions#index'

  get '/v1/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v1/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v1/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v1/users/signup' => 'users#new', as: :signup
  post '/v1/users/signup' => 'users#create'
  get '/v1/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v1/users/password-reset' => 'users#password_reset_request'
  get '/v1/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v1/users/password-new' => 'users#password_update'
  get '/v1/users/:id/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/confirm' => 'users#confirm'
  get '/v1/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  delete '/v1/users/signout' => 'sessions#destroy', as: :signout
  get '/v1/users/:id' => 'users#user_account', as: :user_account
  get '/v1/users/:id/password' => 'users#password_change', as: :password_change
  get '/v1/users/:id/settings' => 'users#settings', as: :user_settings
  delete '/v1/users/:id' => 'users#delete'
  post '/v1/users/:id' => 'users#settings_update'
  put '/v1/users/:id/password/change' => 'users#change_password', as: :user_change_password

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'
  get '/widget' => 'widgets#widget', as: :widget

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  post '/share' => 'sharing#create'
  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/views/shared/_dev_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">

    <ul class="page-sidebar-menu">
      <li>
        <%= link_to cameras_index_path do %>
          <i class="fa fa-camera"></i> Cameras
        <% end %>
      </li>
      <li>
        <a href="/dev"><i class="fa fa-book"></i> Developer</a>
      </li>

      <li class="widgets-menu">
        <a href="<%= widget_live_view_path %>"><i class="fa fa-code"></i> Live View</a>
      </li>

      <li class="widgets-menu">
        <a href="<%= widget_snapshot_navigator_path %>"><i class="fa fa-code"></i> Snapshot Navigator</a>
      </li>

    </ul>
  </div>
</div>

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#dc4c3f">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_header.html.erb
<div class="page-header <%= "camera-#{@camera['id']}" if @camera %> navbar navbar-fixed-top">
  <div class="page-header-inner">
    <div class="menu-toggler sidebar-toggler">
    </div>
    <a href="javascript:;" class="pull-left menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <% if params[:controller] == 'cameras' and params[:action] == 'single' %>
      <div class="camera-switch <% unless @camera['is_online'] %>camera-offline<% end %>">
        <a class="dropdown-toggle" data-toggle="dropdown">
          <span class="status-circle"></span>
          <span class="camera-name"><%= @camera['name'] %></span>
          <span class="camera-caret"><i class="fa fa-caret-down"></i></span>
        </a>
        <ul class="dropdown-menu scroll-menu" role="menu">
          <% @cameras.each do |camera| %>
            <li class="sub-menu-item camera-<%= camera['id'] %> <%= is_active?("/cameras/#{camera['id']}") %> <% unless camera['is_online'] %>sidebar-offline<% end %>">
              <%= link_to camera['name'] , cameras_single_path(camera['id'])%>
              <i class="red header-sidebar fa fa-chain-broken"></i>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<script>
$(document).ready(function () {
  window.initializeHeader();
});
</script>

app/views/shared/_no_script_warning.html.erb
<noscript>
  <div class="noscript-warning">Kindly enable javascript in order to use Evercam properly.</div>
</noscript>

app/views/shared/_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
      <li class="cameras-sidebar">
        <div class="sidebar-title">
          <div id="hello" class="col-md-12">
            <%= link_to cameras_index_path do %>
              <img src="/favicon-white-24x24.png" class="camera-icon"><span class="title"> Cameras</span>
            <% end %>
            <span class="camera-fadrop">
              <i class="fa fa-caret-down pull-right title"></i>
              <i class="fa fa-caret-up pull-right title"></i>
            </span>
          </div>
          <div class="clear-f"></div>
        </div>
      </li>
      <li class="cameralist-height title">
        <ul class="sub-menu sidebar-cameras-list">
          <% @cameras.each do |camera| %>
            <li class="sub-menu-item camera-<%= camera['id'] %> <%= is_active?("/cameras/#{camera['id']}") %> <%= "sidebar-offline" unless camera['is_online'] %>">
              <%= link_to camera['name'], cameras_single_path(camera['id']), data: {"camera-id" => camera['id']} %>
              <i class="red main-sidebar fa fa-chain-broken"></i>
            </li>
          <% end %>
        </ul>
      </li>
      <li class="sidebar-line nprogCall">
        <%= link_to cameras_new_path do %>
        <i class="fa fa-video-camera icon-font"></i><span class="title"> Add IP Camera</span>
        <% end %>
      </li>
      <li class="sidebar-line">
        <%= link_to snapmails_index_path do %>
            <img class="icon-font snapimg" src="//dkzcs7h1dpzak.cloudfront.net/assets/snapmail-fd5f12a06005b85e0247e6fa206e9992c31af9f0c95a79544dcca1f9d216f620.png"><span class="title snapmail-text"> Snapmail</span>
        <% end %>
      </li>
      <li class="nprogCall">
        <%= link_to map_view_path do %>
          <i class="fa fa-map width-20"></i> Map View
        <% end %>
      </li>
      <li class="status-list">
        <%= link_to status_path do %>
          <i class="fa fa-barcode width-20"></i> Status Report
        <% end %>
      </li>
      <li class="nprogCall sidebar-line">
        <%= link_to widget_path do %>
          <i class="fa fa-book"></i> Developer
        <% end %>
      </li>
      <li>
        <a class="seting"><i class="fa fa-cog icon-font"></i> Settings <i class="fa fa-caret-down pull-right"></i>
        <i class="fa fa-caret-up pull-right"></i></a>
        <ul class="setting-list left-nav-submenu">
          <li class="nprogCall">
            <%= link_to user_account_path(current_user.username) do %>
              <i class="fa fa-user width-20"></i> Account
            <% end %>
          </li>
          <li class="nprogCall">
            <%= link_to password_change_path(current_user.username) do %>
              <i class="fa fa-key width-20"></i> Password
            <% end %>
          </li>
        </ul>
      </li>
      <li role="presentation">
        <a id="Intercom"><i class="fa fa-comment icon-font"></i><span class="title"> Live Support</span></a>
      </li>
      <li class="nprogCall">
        <a rel="nofollow" data-method="delete" href=<%= signout_path %>><i class="fa fa-sign-out right-ajustment icon-font"></i><span class="title"> Sign out </span></a>
      </li>
    </ul>
    <input type="hidden" id="controller" value="<%= params[:controller] %>">
    <input type="hidden" id="intercom_api_key" value="<%= intercom_key %>">
  </div>
</div>

app/views/shared/_stripe.html.erb
<% content_for :javascript do %>
  <script type="text/javascript" src="https://js.stripe.com/v2"></script>
<% end %>

app/views/shared/_user_account_sidebar.html.erb
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
    <ul class="page-sidebar-menu">
      <li>
        <%= link_to cameras_index_path do %>
          <i class="fa fa-camera"></i> Cameras
        <% end %>
      </li>
      <li>
        <%= link_to user_account_path(current_user.username) do %>
          <i class="fa fa-user"></i> Account
        <% end %>
      </li>
      <li>
        <%= link_to password_change_path(current_user.username) do %>
          <i class="fa fa-key"></i> Password
        <% end %>
      </li>
      <li>
        <%= link_to user_settings_path(current_user.username) do %>
          <i class="fa fa-cog"></i> Settings
        <% end %>
      </li>
      <li>
        <%= link_to billing_path(current_user.username) do %>
          <i class="fa fa-credit-card"></i> Billing
        <% end %>
      </li>
      <li>
        <%= link_to apps_path(current_user.username) do %>
          <i class="fa fa-wrench"></i> Applications
        <% end %>
      </li>
    </ul>
  </div>
</div>