config/routes.rb
Rails.application.routes.draw do
  get '/v1/users/:id/billing' => 'subscriptions#index', as: :billing
  patch '/v1/users/:id/billing' => 'subscriptions#edit_subscription', as: :edit_subscription
  get '/v1/users/:id/billing/history' => 'subscriptions#billing_history', as: :billing_history
  get '/v1/subscriptions/new' =>'subscriptions#new', as: :new_subscription
  delete '/v1/users/:id/billing' => 'subscriptions#destroy', as: :subscription
  get '/v1/users/:id/billing/sub_data' => 'subscriptions#subscription_data', as: :sub_data

  get '/v1/users/:id/billing/invoices' => 'invoices#index', as: :invoices
  get '/v1/users/:id/billing/invoices/:invoice_id' => 'invoices#show', as: :invoice_show
  get '/v1/users/:id/billing/invoices/:invoice_id/pdf' => 'invoices#create_pdf', as: :create_invoice_pdf
  get '/v1/users/:id/billing/invoices/:invoice_id/send' => 'invoices#send_customer_invoice_email', as: :send_invoic_email
  get '/v1/users/:id/billing/invoices/:custom_id/custom' => 'invoices#custom_user_invoices', as: :custom_show

  delete '/v1/users/:id/billing/add-ons/:add_ons_id' => 'subscriptions#delete_add_ons', as: :delete_add_ons

  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v1/payments' => 'payments#new', as: :new_checkout
  post '/v1/payments' => 'payments#create', as: :new_charge
  post '/v1/users/:id/billing/plans/change' => 'payments#upgrade_downgrade_plan'

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v1/cameras'), as: :root
  get '/v1/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras/new' => 'cameras#new', as: :cameras_new
  get '/v1/cameras/new-test' => 'cameras#addcam_test', as: :cameras_new_test
  post '/v1/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v1/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v1/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v1/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v1/cameras/:id/clip/:clip_id/play' => 'pages#play', as: :play_clip
  get '/v1/cameras/:id/share/request' => 'pages#revoke_request'
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v1/cameras/:id/*subpath' => 'cameras#single'
  get '/v1/users/:id/billing/*subpath' => 'subscriptions#index'

  get '/v1/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v1/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v1/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v1/users/signup' => 'users#new', as: :signup
  post '/v1/users/signup' => 'users#create'
  get '/v1/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v1/users/password-reset' => 'users#password_reset_request'
  get '/v1/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v1/users/password-new' => 'users#password_update'
  get '/v1/users/:id/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/confirm' => 'users#confirm'
  get '/v1/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  delete '/v1/users/signout' => 'sessions#destroy', as: :signout
  get '/v1/users/:id' => 'users#user_account', as: :user_account
  get '/v1/users/:id/password' => 'users#password_change', as: :password_change
  get '/v1/users/:id/settings' => 'users#settings', as: :user_settings
  delete '/v1/users/:id' => 'users#delete'
  post '/v1/users/:id' => 'users#settings_update'
  put '/v1/users/:id/password/change' => 'users#change_password', as: :user_change_password

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'
  get '/widget' => 'widgets#widget', as: :widget

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  post '/share' => 'sharing#create'
  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :owns_data!
  layout "user-account"
  include SessionsHelper
  include ApplicationHelper
  include StripeCustomersHelper
  include StripeInvoicesHelper
  # require "stripe"
  # require "date"

  def index
    if current_user.insight_id.present?
      @insight_url = "#{ENV['INSIGHT_URL']}AuthKey=#{ENV['invoice_auth_key']}&JSONObject&CustomerCode=#{current_user.insight_id}"
    end
    @cameras = load_user_cameras(true, false)
    set_prices
    @next_charge = retrieve_customer_next_charge
    @cameras_products = Camera.where(owner: current_user).eager(:cloud_recording).all
    @custom_licence = Licence.where(user_id: current_user.id).where(cancel_licence: false, subscription_id: nil)
    unless current_user.stripe_customer_id.blank?
      @credit_cards = retrieve_credit_cards
      @subscriptions = has_subscriptions? ? retrieve_stripe_subscriptions : nil
    end
    retrieve_plans_quantity(@subscriptions)
  end

  def billing_history
    if params[:invoice_id]
      description = retrieve_customer_plan(params[:invoice_id])
      render json: { description: description }
    elsif params[:invoices]
      invoices = retrieve_customer_invoices
      render json: invoices
    else
      billing_history = retrieve_customer_billing_history
      render json: billing_history
    end
  end

  def new
    @cameras = load_user_cameras(true, false)
    render layout: false
  end

  def create
    stripe_customer = retrieve_stripe_customer
    stripe_customer.subscription.create(:plan => params[:plan_id])
    flash[:message] = "You have successfuly created a new #{params[:plan_name]} subscription."
    redirect_to user_path(current_user.username)
  end

  def destroy
    subscription = Stripe::Subscription.retrieve(params[:subscription_id])
    subscription.delete(:at_period_end => true)
    render json: {result: true}
  end

  def delete_add_ons
    begin
      if params[:add_ons_id].present?
        add_on = AddOn.find(id: params[:add_ons_id])
        delete_invoice_item(add_on.invoice_item_id, add_on.price.to_i, add_on.add_ons_name)
        flash[:message] = "You have successfuly deleted your '#{add_on.add_ons_name}' add-on."
        add_on.delete()
      else
        flash[:message] = "Invalid add-ons id specified."
      end
    rescue => _error
      flash[:message] = "An error occurred while deleting add-ons. "\
                      "Please try again and, if the problem persists, contact "\
                      "support."
    end
    redirect_to billing_path(current_user.username)
  end

  def edit_subscription
    subscription = Stripe::Subscription.retrieve(params[:subscription_id])
    subscription.plan = params[:plan]
    subscription.quantity = params[:quantity].to_i
    subscription.save
    render json: {result: true}
  end

  def subscription_data
    subscription =  has_subscriptions? ? retrieve_stripe_subscriptions : nil
    render json: {subscription: subscription[:data]}
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def has_subscription?
    @subscription.present?
  end
  def cart_empty?
    session[:cart].empty?
  end
end

app/views/subscriptions/_add_card.html.erb
<% unless is_stripe_customer? %>
  <form action="<%= stripe_customers_path -%>" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] -%>"
    data-image="<%= asset_path('evercam-e.svg') -%>"
    data-email="<%= current_user.email -%>"
    data-allowRememberMe="false"
    data-name="Evercam"
    data-description="Add a Card"
    data-panelLabel="Add Card"
    data-label="Add Card">
    </script>
  </form>
<% end %>

<% if is_stripe_customer? %>
  <div>
    <form action="<%= credit_cards_path -%>" method="POST">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] -%>"
      data-image="<%= asset_path('evercam-e.svg') -%>"
      data-email="<%= current_user.email -%>"
      data-allowRememberMe="false"
      data-name="Evercam"
      value="Add Card"
      data-description="Add a new Card"
      data-panelLabel="Add new Card"
      data-label="Add new Card">
      </script>
    </form>
  </div>
<% end %>

app/views/subscriptions/_cart.html.erb
<%= render "subscriptions/checkout" %>

app/views/subscriptions/_checkout.html.erb
<section class="cart">
  <% unless cart_empty? %>
    <% sub_totle = 0 %>
    <% add_ons_total = 0 %>
    <table class="table table-borderless">
      <tr>
        <th class="col-md-2">Product</th>
        <th class="col-md-1 text-center">Qty.</th>
        <th class="col-md-2 text-right">Unit Price</th>
      </tr>
      <% session[:cart].each do |item| %>
        <tr>
          <td class="col-md-4 text-left"><%= item.name %>  <small><%= link_to 'remove', line_item_path({id: item.id, product: item.product_id.gsub('-annual',''), type: item.type}), method: :delete, remote: true, class: 'padding-left-10' %></small> </td>
          <td class="col-md-1 text-center"><%= item.quantity %></td>
          <td class="col-md-2 text-right"><%= cents_to_currency item.price %> </td>
        </tr>
        <% add_ons_total = add_ons_total + item.price if item.type.eql?("add_on") %>
        <% sub_totle = sub_totle + item.price * item.quantity.to_i %>
      <% end %>
    </table>
    <div class="sub-container text-right">
      <% if add_ons_in_cart? %>
        <!--<li>Add-ons Subtotal to Renewal: <%# cents_to_currency(@pro_rated_add_ons_charge) %></li>-->
        <p>
          <span class="sub-total blue">Add-ons Total: </span>
          <span class="pull-right"><%= cents_to_currency(add_ons_total) %></span>
        </p>
      <% end %>
      <p>
        <span class="bold sub-total blue">Total:  </span>
        <span class="bold pull-right"> <%= cents_to_currency sub_totle %></span>
        <input type="hidden" id="total-price" value="<%= cents_to_currency sub_totle %>">
      </p>
    </div>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
  <input type="hidden" id="cart-total" value="<%= session[:cart].count %>">
</section>

app/views/subscriptions/_invoices.html.erb
<div class="custom_licences">
  <h3 class="margin-left-15">Custom Invoices</h3>
  <div class="col-md-12">
    <table id="custom-invoices" style="width:100%;" class="table table-full-width">
      <thead>
      <tr>
        <th class="col-md-2">Inv #</th>
        <th class="col-md-2">Date</th>
        <th class="col-md-2">Reference</th>
        <th class="col-md-2">Amount €</th>
        <th class="col-md-2">Due €</th>
        <th class="col-md-2">Next Create Date</th>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>

<input id="insight-custom-url" type="hidden" value=<%= @insight_url %>>
<input id="insight-id" type="hidden" value=<%= current_user.insight_id %>>

app/views/subscriptions/_subscriptions.erb
<div class="subscriptions">
  <div class="col-md-4">
    <% if @subscriptions.present? %>
      <h3 class="marg">Subscriptions</h3>
    <% elsif has_credit_cards? == false %>
      <h4>Please add a credit card</h4>
    <% else %>
      <h4>Add a new subscription</h4>
    <% end %>
  </div>
  <div class="col-md-8 licence-alert alert alert-danger" style="display:none">
    <span id="licence-message">You require <span class="licence-message-7"> (7 days) ,</span><span class="licence-message-30"> (30 days) ,</span><span class="licence-message-90"> (90 days) ,</span><span class="licence-message-infinity"> (infinity) </span> additional Plans.</span>
  </div>
  <% if @subscriptions.present? %>
  <div class="col-md-12">
    <table id="subscription_data" class="subscription-table table table-striped table-bordered" cellspacing="0" width="100%">
      <tr>
        <div id="img-subscription-loader" class="img-subscription-loader middle-gif hide">
          <%= image_tag('loader3.gif', alt: 'Loading') %>
        </div>
        <thead>
        <th class="col-md-2">Plan</th>
        <th class="col-md-1">Quantity</th>
        <th class="col-md-1">Price (<i class='fa fa-eur'></i>)</th>
        <th class="col-md-2">Created On</th>
        <th class="col-md-1">Period</th>
        <th class="col-md-2">Auto-Renewal</th>
        <th class="col-md-2">Next Renewal On</th>
        <th class="col-md-1">Options</th>
      </tr>
      </thead>
    </table>
  </div>
  <% end %>
  <div class="col-md-12 margin-bottom-40">
    <input id="open-modal" class="btn btn-primary save-sub-button" value="Add Subscription" type="button">
  </div>
</div>

app/views/subscriptions/index.html.erb
<%= content_for(:title, " Evercam: Billing ") %>

<div class="bb-alert alert alert-info" style="display:none;">
  <span></span>
</div>
<div class="subscriptions page-content-wrapper">
  <div class="page-content">
    <div class="portlet-body">
      <div class="tabbable tabbable-custom">
        <div class="center-tabs">
          <ul id="ul-nav-tab" class="nav nav-tabs">
            <li class="active">
              <a data-toggle="tab" data-target="#subscriptions" class="nav-tab-subscriptions">Subscriptions</a>
            </li>
            <% if current_user.insight_id.present? %>
                <li>
                  <a data-toggle="tab" data-target="#invoices" class="nav-tab-custom">Custom</a>
                </li>
            <% end %>
            <li>
              <a data-toggle="tab" data-target="#paymenthistory" class="nav-tab-paymenthistory">Payment History</a>
            </li>
            <li>
              <a data-toggle="tab" data-target="#cards" class="nav-tab-cards">Credit Cards</a>
            </li>
          </ul>
        </div>
        <div class="tab-content">
          <div id="paymenthistory" class="tab-pane">
            <%= render partial: "subscriptions/history/history_tab" %>
          </div>
          <div id="cards" class="tab-pane">
            <%= render partial: "subscriptions/cards/cards_tab" %>
          </div>
          <div id="subscriptions" class="tab-pane active">
            <%= render partial: "subscriptions/subscriptions" %>
          </div>
          <div id="invoices" class="tab-pane">
            <%= render partial: "subscriptions/invoices" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div id="edit-modal" class="modal fade edit-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class='col-lg-12 col-md-12 col-sm-12'>
            <div class='portlet'>
              <div class="portlet-title">
                <div class="caption col-md-12"> Edit subscription </div>
                <div class="color-grey">*Edit your subscription by changing the Plan and Quantity.</div>
              </div>
              <div class="portlet-body">
                <div class="add-clip">
                  <table class="table table-fixed table-borderless">
                    <tr>
                      <td style="width: 100px;"><label class="control-label quantity" >Plan:</label></td>
                      </td>
                      <td>
                        <select id="sub-type" name="sub-type" class="form-control">
                          <option data-price=10 value="7-days-recording">7 days recording</option>
                          <option data-price=20 value="30-days-recording">30 days recording</option>
                          <option data-price=30 value="90-days-recording">90 days recording</option>
                          <option data-price=100 value="7-days-recording-annual">7 days recording annual</option>
                          <option data-price=200 value="30-days-recording-annual">30 days recording annual</option>
                          <option data-price=300 value="90-days-recording-annual">90 days recording annual</option>
                        </select>
                      </td>
                    </tr>
                    <tr>
                      <td style="width: 100px;"><label class="control-label quantity" >Quantity:</label></td>
                      <td>
                        <input type="text" class="form-control makeEditable" id="sub-quantity">
                      </td>
                    </tr>
                    <tr>
                      <td style="width: 100px;"><label class="control-label price" >Total Price:</label></td>
                      <td>
                        <span class="form-control" id="sub-price"><i class='fa fa-eur'></i></span>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <fieldset>
          <div class="save-settings">
            <div class='pull-left form-group'><label class="control-label" for="add-button"></label>
              <input type="button" class="alert push btn btn-primary margin-right-10" subscription_id="" id="edit_subs" value="Save"/>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
</div>

<div id="add-modal" class="modal fade add-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="row">
          <div class='col-lg-12 col-md-12 col-sm-12'>
            <div class='portlet'>
              <div class="portlet-title">
                <div class="caption"> Add Subscription </div>
              </div>
              <div class="portlet-body">
                <div class="add-clip">
                  <table class="table table-fixed table-borderless">
                    <tr>
                      <td style="width: 100px;"><label class="control-label quantity" >Plan:</label></td>
                      </td>
                      <td>
                        <select id="sub-type" name="sub-type" class="form-control">
                          <option data-price=10 value="7-days-recording">7 days recording</option>
                          <option data-price=20 value="30-days-recording">30 days recording</option>
                          <option data-price=30 value="90-days-recording">90 days recording</option>
                          <option data-price=100 value="7-days-recording-annual">7 days recording annual</option>
                          <option data-price=200 value="30-days-recording-annual">30 days recording annual</option>
                          <option data-price=300 value="90-days-recording-annual">90 days recording annual</option>
                        </select>
                      </td>
                    </tr>
                    <tr>
                      <td style="width: 100px;"><label class="control-label quantity" >Quantity:</label></td>
                      <td>
                        <input type="text" class="form-control makeEditable" id="sub-quantity" value="1">
                      </td>
                    </tr>
                    <tr>
                      <td style="width: 100px;"><label class="control-label price" >Total Price:</label></td>
                      <td>
                        <span class="form-control" id="sub-price"><i class='fa fa-eur'></i></span>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <fieldset>
          <div class="save-settings">
            <div class='pull-left form-group'><label class="control-label" for="add-button"></label>
              <input type="button" class="alert push btn btn-primary margin-right-10" id="add_subs" value="Save"/>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </fieldset>
      </div>
    </div>
  </div>
</div>
<% one_day = []
   seven = []
   thirty = []
   ninety = []
   infinity = []
   @cameras_products.each do |camera|
     if camera.cloud_recording.present? && !camera.cloud_recording.status.eql?("off")
       if camera.cloud_recording.storage_duration.equal?(-1)
         infinity[infinity.count] = camera
       elsif  camera.cloud_recording.storage_duration.equal?(7)
         seven[seven.count] = camera
       elsif  camera.cloud_recording.storage_duration.equal?(30)
         thirty[thirty.count] = camera
       elsif  camera.cloud_recording.storage_duration.equal?(90)
         ninety[ninety.count] = camera
       end
     end
   end %>

<input type="hidden" id="licence-required-seven-day" value="<%= seven.count %>">
<input type="hidden" id="licence-required-thirty-day" value="<%= thirty.count %>">
<input type="hidden" id="licence-required-ninety-day" value="<%= ninety.count %>">
<input type="hidden" id="7-days-recording-current-qty" value="<%= @seven_days_recording.to_i + @seven_days_recording_annual.to_i %>">
<input type="hidden" id="30-days-recording-current-qty" value="<%= @thirty_days_recording.to_i + @thirty_days_recording_annual.to_i %>">
<input type="hidden" id="90-days-recording-current-qty" value="<%= @ninety_days_recording.to_i + @ninety_days_recording_annual.to_i %>">
<input type="hidden" id="has-credit-card" value="<%= has_credit_cards? %>">
<input type="hidden" id="sub-url" value="/v1/users/<%= current_user.username %>/billing/sub_data">
<input type="hidden" id="subs-all" value="<%= @subscriptions %>">

<script>
  window.initializeSubscription();
  <% if flash[:message] %>
  Notification.show('<%= flash[:message] %>');
  <% end %>
</script>