config/routes.rb
Rails.application.routes.draw do
  get '/v1/users/:id/billing' => 'subscriptions#index', as: :billing
  patch '/v1/users/:id/billing' => 'subscriptions#edit_subscription', as: :edit_subscription
  get '/v1/users/:id/billing/history' => 'subscriptions#billing_history', as: :billing_history
  get '/v1/subscriptions/new' =>'subscriptions#new', as: :new_subscription
  delete '/v1/users/:id/billing' => 'subscriptions#destroy', as: :subscription
  get '/v1/users/:id/billing/sub_data' => 'subscriptions#subscription_data', as: :sub_data

  get '/v1/users/:id/billing/invoices' => 'invoices#index', as: :invoices
  get '/v1/users/:id/billing/invoices/:invoice_id' => 'invoices#show', as: :invoice_show
  get '/v1/users/:id/billing/invoices/:invoice_id/pdf' => 'invoices#create_pdf', as: :create_invoice_pdf
  get '/v1/users/:id/billing/invoices/:invoice_id/send' => 'invoices#send_customer_invoice_email', as: :send_invoic_email
  get '/v1/users/:id/billing/invoices/:custom_id/custom' => 'invoices#custom_user_invoices', as: :custom_show

  delete '/v1/users/:id/billing/add-ons/:add_ons_id' => 'subscriptions#delete_add_ons', as: :delete_add_ons

  get '/pay' => 'payments#pay', as: :pay
  get '/thank-for-payment' => 'payments#thank', as: :thank_payment
  post '/pay' => 'payments#make_payment', as: :make_payment
  get '/v1/payments' => 'payments#new', as: :new_checkout
  post '/v1/payments' => 'payments#create', as: :new_charge
  post '/v1/users/:id/billing/plans/change' => 'payments#upgrade_downgrade_plan'

  # These routes are for managing customer cards on Stripe
  resources :stripe_customers, only: [:create, :update]
  resources :credit_cards, only: [:create, :destroy]

  resources :line_items, only: [:destroy]
  post 'line_items/create_subscription' => 'line_items#create_subscription', as: :line_item_subscription
  post 'line_items/create_add_on' => 'line_items#create_add_on', as: :line_item_add_on

  mount StripeEvent::Engine => '/stripe-events'

  root to: redirect('/v1/cameras'), as: :root
  get '/v1/cameras' => 'cameras#index', as: :cameras_index
  get '/v1/cameras/new' => 'cameras#new', as: :cameras_new
  get '/v1/cameras/new-test' => 'cameras#addcam_test', as: :cameras_new_test
  post '/v1/cameras/new' => 'cameras#create'
  get '/cameras/transfer' => 'cameras#transfer'
  get '/status' => 'cameras#online_offline'
  get '/status_report' => 'cameras#update_status_report'
  get '/map' => 'cameras#map', as: :map_view
  get '/table' => 'cameras#cameras_table'
  get '/v1/cameras/:id' => 'cameras#single', as: :cameras_single
  get '/v1/cameras/:id/clone' => 'cameras#new', as: :cameras_clone
  get '/v1/cameras/:id/404' => 'cameras#camera_not_found', as: :cameras_not_found
  patch '/v1/cameras/:id' => 'cameras#update'
  delete '/cameras/:id' => 'cameras#delete'
  post 'cameras/:id/request_clip' => 'cameras#request_clip', as: :request_clip
  delete 'cameras/clip/delete' => 'cameras#delete_clip', as: :delete_clip
  get '/v1/cameras/:id/clip/:clip_id/play' => 'pages#play', as: :play_clip
  get '/v1/cameras/:id/share/request' => 'pages#revoke_request'
  post '/log_intercom' => 'cameras#log_intercom'
  get '/single_camera_status_bar' => 'cameras#status_bar_single_camera'
  get '/server_down' => 'cameras#server_down', as: :server_down

  get '/v1/cameras/:id/*subpath' => 'cameras#single'
  get '/v1/users/:id/billing/*subpath' => 'subscriptions#index'

  get '/v1/snapmails' => 'snapmails#index', as: :snapmails_index
  get '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribe'
  post '/v1/snapmails/:id/unsubscribe' => 'pages#unsubscribed', as: :unsubscribed_snapmail

  get '/timelapses' => 'timelapses#index', as: :timelapses_index

  get '/v1/public/cameras' => redirect('https://evercam.io/public/cameras/')
  get '/v1/public/cameras/:id' => redirect('https://evercam.io/public/cameras/')

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit]
  get '/sessions' => redirect('/')

  get '/v1/users/signup' => 'users#new', as: :signup
  post '/v1/users/signup' => 'users#create'
  get '/v1/users/password-reset' => 'users#password_reset_request', as: :password_reset
  post '/v1/users/password-reset' => 'users#password_reset_request'
  get '/v1/users/password-new' => 'users#password_update_form', as: :password_new
  post '/v1/users/password-new' => 'users#password_update'
  get '/v1/users/:id/resend' => 'users#resend_confirmation_email', as: :user_email_resend
  get '/confirm' => 'users#confirm'
  get '/v1/users/signin' => 'sessions#new', as: :signin
  get '/widget_signin' => 'sessions#widget_new', as: :widget_signin
  delete '/v1/users/signout' => 'sessions#destroy', as: :signout
  get '/v1/users/:id' => 'users#user_account', as: :user_account
  get '/v1/users/:id/password' => 'users#password_change', as: :password_change
  get '/v1/users/:id/settings' => 'users#settings', as: :user_settings
  delete '/v1/users/:id' => 'users#delete'
  post '/v1/users/:id' => 'users#settings_update'
  put '/v1/users/:id/password/change' => 'users#change_password', as: :user_change_password

  get '/widgets-new' => 'widgets#widgets_new', as: :widget_live_view
  get '/live.view.widget' => 'widgets#live_view_widget'
  get '/live.view.private.widget' => 'widgets#live_view_private_widget'
  get '/widgets-hikvision' => 'widgets#widgets_hikvision', as: :widget_hikvision
  get '/hikvision.local.storage' => 'widgets#hikvision_local_storage'
  get '/hikvision.private.widget' => 'widgets#hikvision_private_widget'

  get '/widgets-snapshot-navigator' => 'widgets#widget_snapshot_navigator', as: :widget_snapshot_navigator
  get '/snapshot.navigator.widget' => 'widgets#snapshot_navigator_widget'
  get '/snapshot.navigator' => 'widgets#snapshot_navigator'
  get '/widget' => 'widgets#widget', as: :widget

  namespace :widgets do
    resources :widget_cameras_add, path: :widget_cameras_add
    get '/cameras/add' => 'widget_cameras_add#widget_add_camera', as: :widget_camera_add
    get '/cameras/public/add' => 'widget_cameras_add#add_public_camera'
    get '/add.camera' => 'widget_cameras_add#add_camera'

    resources :widget_timelapse, path: :widget_timelapse
    get '/timelapse-widget' => 'widget_timelapse#timelapse_js'
  end

  get '/live/:id' => 'pages#live'
  get '/good_bye' => 'pages#good_bye', as: :good_bye
  get '/nvr-recordings' => 'pages#nvr_recording'

  post '/share' => 'sharing#create'
  delete '/share' => 'sharing#delete'
  post '/share/camera/:id' => 'sharing#update_camera'
  delete '/share/request' => 'sharing#cancel_share_request'
  post '/share/request/resend' => 'sharing#resend_share_request'
  patch '/share/request' => 'sharing#update_share_request'
  patch '/share/:id' => 'sharing#update_share'

  get '*path' => 'pages#log_and_redirect'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_when_cart_empty, only: :new
  prepend_before_action :ensure_card_exists, only: [:create, :new]
  prepend_before_action :customer_id_exists, only: [:ensure_card_exists]
  skip_before_action :authenticate_user!, only: [:pay, :make_payment, :thank]
  layout "user-account"
  include SessionsHelper
  include ApplicationHelper
  include CurrentCart
  include StripeCustomersHelper
  include StripeInvoicesHelper
  require "stripe"

  def pay
    render layout: "bare-bones"
  end

  def thank
    render layout: "bare-bones"
  end

  def make_payment
    begin
      token = create_token(params)
      response = make_custom_payment(params, token)
      redirect_to thank_payment_path
    rescue => error
      flash[:error] = error.message
      redirect_to pay_path
    end
  end

  # This is the view checkout action
  def new
    @customer = retrieve_stripe_customer
    @total_charge = total_charge
    @pro_rated_add_ons_charge = pro_rated_add_ons_charge
    @add_ons_charge = add_ons_charge
    @cameras = load_user_cameras(true, false)
    @card = retrieve_credit_cards[:data][0]
  end

  def create
    buy_subscription(params[:plan], params[:quantity].to_i)
    flash[:message] = 'You have succesfully added a new subscription!'
    render json: {result: true}
  end

  def upgrade_downgrade_plan
    result = {success: true}
    begin
      product_params = build_line_item_params(params)
      product_params[:quantity] = params[:quantity]
      @line_item = LineItem.new(product_params)
      @customer = retrieve_stripe_customer_without_cart(@line_item)
      @customer.change_plan
    rescue => error
      Rails.logger.warn "Exception caught while upgrade/downgrade plan.\n"\
                              "Cause: #{error}\n" + error.backtrace.join("\n")
      result[:success] = false
      result[:message] = "Somethings gone wrong. We failed to change your plan."
    end
    render json: result
  end

  private

  def create_token(params)
    Stripe::Token.create(
      :card => {
        :number => params["card-number"],
        :exp_month => params["expiry-month"],
        :exp_year => params["expiry-year"],
        :cvc => params["card-cvc"]
      },
    )
  end

  def make_custom_payment(params, token)
    amount = params[:amount].to_f * 100
    Stripe::Charge.create(
      :amount => amount.to_i,
      :currency => "eur",
      :source => token.id,
      :description => "Charge for #{params[:email]}"
    )
  end

  def buy_subscription(plan, quantity)
    selector = ProductSelector.new(plan)
    product_params = selector.product_params
    product_params[:quantity] = quantity
    storage = product_params[:storage]
    @line_item = LineItem.new(product_params)
    @customer = retrieve_stripe_customer_without_cart(@line_item)
    subscription = @customer.create_subscription
    save_licence(subscription, storage)
  end

  def save_licence(subscription, storage)
    licence = Licence.new(
      user_id: current_user.id,
      subscription_id: subscription.id,
      description: subscription.plan.name,
      total_cameras: subscription.quantity,
      storage: storage,
      amount: subscription.plan.amount,
      start_date: Time.at(subscription.current_period_start),
      end_date: Time.at(subscription.current_period_end),
      created_at: Time.at(subscription.start),
      auto_renew: !subscription.cancel_at_period_end,
      paid: true
    )
    licence.save
  end

  def update_subscription(plan, subscription_id, quantity)
    selector = ProductSelector.new(plan)
    product_params = selector.product_params
    product_params[:quantity] = quantity
    storage = product_params[:storage]
    @line_item = LineItem.new(product_params)
    @customer = retrieve_stripe_customer_without_cart(@line_item)
    subscription = @customer.update_subscription(subscription_id)
    update_licence(subscription, storage)
  end

  def update_licence(subscription, storage)
    licence = Licence.where(subscription_id: subscription.id).first
    licence.description = subscription.plan.name
    licence.total_cameras = subscription.quantity
    licence.storage = storage
    licence.amount = subscription.plan.amount
    licence.start_date = Time.at(subscription.current_period_start)
    licence.end_date = Time.at(subscription.current_period_end)
    licence.created_at = Time.at(subscription.start)
    licence.auto_renew = !subscription.cancel_at_period_end
    licence.paid = true
    licence.save
  end

  def cancel_subscription(subscription_id)
    @customer = StripeCustomer.new(current_user.stripe_customer_id)
    @customer.cancel_subscription(subscription_id)
    licence = Licence.where(subscription_id: subscription_id).first
    licence.cancel_licence = true
    licence.save
  end

  def build_line_item_params params
    selector = ProductSelector.new(params[:plan_id])
    selector.product_params
  end

  def redirect_when_cart_empty
    if session[:cart].nil?
      redirect_to billing_path(current_user.username), flash: {message: "You have nothing to checkout"}
    end
  end

  def ensure_card_exists
    @customer = StripeCustomer.new(current_user.stripe_customer_id)
    unless @customer.valid_card?
      redirect_to billing_path(current_user.username), flash: { message: "You need to add a card first!" }
    end
  end

  def customer_id_exists
    if current_user.stripe_customer_id.nil?
      redirect_to billing_path(current_user.username), flash: { message: "You need to add a card first!" }
    end
  end

  def ensure_plan_in_cart_or_existing_subscriber
    unless @customer.has_active_subscription? || plan_in_cart?
      redirect_to billing_path(current_user.username), flash: { message: "You must select a plan" }
    end
  end

  def retrieve_stripe_customer
    StripeCustomer.new(current_user.stripe_customer_id, plan_in_cart)
  end

  def retrieve_stripe_customer_without_cart(product)
    StripeCustomer.new(current_user.stripe_customer_id, product)
  end

  def create_subscription
    @customer.create_subscription
    purge_plan_from_cart
    flash[:message] = "Plan created."
  rescue
    flash[:error] = "Something went wrong."
  end

  def change_plan
    @customer.change_plan
    purge_plan_from_cart
    flash[:message] = "Plan Changed."
  rescue
    flash[:error] = "Something went wrong."
  end

  # Make a new call to Stripe to refresh the subscription data
  def create_charge
    @customer = retrieve_stripe_customer
    @customer.create_charge(pro_rated_add_ons_charge, charge_description)
    insert_add_ons
    empty_cart
  rescue
    flash[:error] = "Something went wrong."
  end

  def pro_rate_percentage
    if @customer.current_plan && (Time.now.getutc.to_i - @customer.current_plan.created) >= 600
      month_period = @customer.current_subscription.current_period_end - @customer.current_subscription.current_period_start
      add_on_period = @customer.current_subscription.current_period_end - Time.now.getutc.to_i
      ((add_on_period.to_f / month_period.to_f) * 100)
    else
      100
    end
  end

  def pro_rated_add_ons_charge
    if add_ons_in_cart?
      ((add_ons_charge / 100) * pro_rate_percentage).to_i
    else
      nil
    end
  end

  def add_ons_charge
    amounts = add_ons_in_cart.map { |item| item.price }
    amounts.inject(0) {|sum, i|  sum + i }
  end

  # For an accurate subtotal of a mid term change, this method should also query Stripe for the pro rata change if the user switches plans.
  def total_charge
    pro_rated_add_ons_charge.present? ? pro_rated_add_ons_charge + plan_cost : calculate_total
  end

  def charge_description
    description = ''
    add_ons_in_cart.each_with_index do |item, index|
        description.concat(item.name)
        unless index.eql?(add_ons_in_cart.length - 1)
          description.concat(', ')
        else
          description.concat('.')
        end
      end
    description
  end

  def insert_add_ons
    add_ons_in_cart.each_with_index do |item, index|
      begin
        has_add_on = AddOn.where(user_id: current_user.id, exid: item.product_id)
        if has_add_on.blank?
          invoice_item = add_invoice_item(item.price, item.name, 1)
          invoice_item_id = invoice_item.id
        else
          invoice_item_id = has_add_on.first.invoice_item_id
          update_invoice_item(invoice_item_id, item.price, item.name, has_add_on.count + 1)
        end
        add_update_add_on(item, invoice_item_id)
      rescue => _error
      end
    end
  end

  def add_update_add_on(item, invoice_item_id)
    AddOn.create(user_id: current_user.id,
                 exid: item.product_id,
                 add_ons_name: item.name,
                 period: item.interval,
                 add_ons_start_date: DateTime.now(),
                 add_ons_end_date: calculateadd_ons_end_date(item),
                 status: true,
                 price: item.price,
                 invoice_item_id: invoice_item_id)
  end

  def calculateadd_ons_end_date add_on
    if add_on.interval.eql?('month')
      DateTime.now()+30.days
    else
      DateTime.now()+1.year
    end
  end

  def product_price(product_id)
    case product_id
    when "evercam-free"
      @prices.evercam_free
    when "evercam-free-annual"
      @prices.evercam_free_annual
    when "evercam-pro"
      @prices.evercam_pro
    when "evercam-pro-annual"
      @prices.evercam_pro_annual
    when "evercam-pro-plus"
      @prices.evercam_pro_plus
    when "evercam-pro-plus-annual"
      @prices.evercam_pro_plus_annual
    when "snapmail"
      @prices.snapmail
    when "snapmail-annual"
      @prices.snapmail_annual
    when "timelapse"
      @prices.timelapse
    when "timelapse-annual"
      @prices.timelapse_annual
    when "7-days-recording"
      @prices.seven_days_recording
    when "7-days-recording-annual"
      @prices.seven_days_recording_annual
    when "30-days-recording"
      @prices.thirty_days_recording

app/helpers/payments_helper.rb
module PaymentsHelper
  def add_ons_in_cart?
    session[:cart].detect {|i| i.type.eql?('add_on') } ? true : false
  rescue
    nil
  end
end

app/views/payments/new.html.erb
<div class="checkout-page page-content-wrapper">
  <div id="payNowModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="col-md-12">
            <p class="text-left margin-top-10">
              <strong><%= cents_to_currency(@total_charge) %></strong> will be charged from your <strong><%= @card.brand %></strong> card ending in <strong><%= @card.last4 %></strong></p>
          </div>
        </div>
        <div class="modal-footer">
          <div class="col-sm-8">
            <%= button_to "Pay Now", new_charge_path({ amount: @total_charge }), class: 'btn btn-primary pull-left' %>&nbsp;
            <input type="button" class="btn btn-default pull-left margin-left2" value="Cancel" data-dismiss="modal" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-content">
    <div class="plans">

      <div class="col-md-6">
        <h3>Review your Order</h3>
          <%= render "subscriptions/checkout" %>
          <!--Total <%# cents_to_currency(@total_charge) %>-->
          <%# if add_ons_in_cart? %>
        <!--<li>Add-ons Subtotal to Renewal: <%# cents_to_currency(@pro_rated_add_ons_charge) %></li>
            <li>Add-ons per month: <%# cents_to_currency(@add_ons_charge) %></li>-->
          <%# end %>
          <a class="btn btn-primary pull-right" data-toggle="modal" data-target="#payNowModal">Pay Now</a>
      </div>
    </div>
  </div>
</div>

app/views/payments/pay.html.erb
<section id="make-payment-section">
  <div class="container section">
    <div id="signin" class="col-md-12 text-center">
      <div class="bb-alert alert alert-danger" style="display:none;">
        <span></span>
      </div>
      <div class="branding margin-bottom-50">
        <%= link_to root_path, class: 'sign-in-logo' do %>
          <%= image_tag("evercam_logo.png", :class => "svg-logo", alt: "Evercam.io") %>
        <% end %>
      </div>
    </div>

    <div id="sign-in" class="make-payment col-md-6 col-md-offset-3">
      <h3 class="text-center">PAY WITH CARD</h3>
      <form action="<%= make_payment_path %>" method="post" id="example-form">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <div class="col-md-10 col-md-offset-1">
          <label for="email">E-mail Address</label>
          <div class="input-icon right">
            <i class="fa fa-envelope"></i>
            <input type="text" name="email" id="email" class="required" />
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <label for="reference">Reference Number</label>
          <div class="input-icon right">
            <i class="fa fa-euroa">#</i>
            <input type="text" name="reference" class="required" />
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <label for="amount">Payment Amount</label>
          <div class="input-icon right">
            <i class="fa fa-euro"></i>
            <input type="text" name="amount" id="amount" class="required" placeholder="9.99"/>
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-6 adjust-padding-col1">
            <div class="row1">
              <label for="name" class="stripeLabel">Card Holder's Name</label>
              <input type="text" name="name" id="name" class="required" />
            </div>
          </div>
          <div class="col-md-6 adjust-padding-col2">
            <div class="row1">
              <label>Card Number</label>
              <input id="card-number" name="card-number" type="text" maxlength="20" autocomplete="off" class="card-number stripe-sensitive required" />
            </div>
          </div>
        </div>

        <div class="col-md-10 col-md-offset-1">
          <ul class="cards unstyled">
            <li>
              <span class="card amex" title="American Express">AMEX</span>
            </li>
            <li>
              <span class="card master" title="Mastercard">MC</span>
            </li>
            <li>
              <span class="card visa" title="Visa">VISA</span>
            </li>
            <li>
              <span class="card stripe" title="stripe">stripe</span>
            </li>
          </ul>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <div class="col-md-4 adjust-padding-col1">
            <label>Card CVC</label>
            <input name="card-cvc" id="card-cvc" type="text" maxlength="4" autocomplete="off" class="card-cvc stripe-sensitive required" />
          </div>
          <div class="col-md-4 adjust-padding-col1">
            <label>Month</label>
            <select name="expiry-month" id="expiry-month" class="form-control card-expiry-month expiry-drop-down">
            </select>
            <script type="text/javascript">
              var select = $(".card-expiry-month"),
                month = new Date().getMonth() + 1;
              for (var i = 1; i <= 12; i++) {
                select.append($("<option value='"+i+"' "+(month === i ? "selected" : "")+">"+i+"</option>"))
              }
            </script>
          </div>
          <div class="col-md-4 adjust-padding-col2">
            <label>Year</label>
            <select name="expiry-year" id="expiry-year" class=" form-control card-expiry-year expiry-drop-down"></select>
            <script type="text/javascript">
              var select = $(".card-expiry-year"),
                year = new Date().getFullYear();
              for (var i = 0; i < 12; i++) {
                select.append($("<option value='"+(i + year)+"' "+(i === 0 ? "selected" : "")+">"+(i + year)+"</option>"))
              }
            </script>
          </div>
        </div>
        <div class="col-md-10 col-md-offset-1 margin-top-20">
          <button class="btn btn-large btn-primary col-lg-10 col-lg-offset-1" type="submit" name="submit-button" id="submit-button">Make Payment</button>
          <span class="payment-errors"></span>
        </div>
      </form>
    </div>

    <div class="grey col-md-4 col-md-offset-4 row text-center margin-top-20">
      <p> <%= link_to "Sign in", signin_path %></p>
    </div>
  </div>
</section>

<script>
  window.initializePay();
  Notification.init(".bb-alert");
  <% if flash[:error] %>
  Notification.show('<%= flash[:error] %>');
  <% end %>
</script>

app/views/payments/thank.html.erb
<section id="make-payment-section">
  <div class="container section">
    <div id="signin" class="col-md-12 text-center">
      <div class="bb-alert alert alert-danger" style="display:none;">
        <span></span>
      </div>
      <div class="branding margin-bottom-50">
        <%= link_to root_path, class: 'sign-in-logo' do %>
          <%= image_tag("evercam_logo.png", :class => "svg-logo", alt: "Evercam.io") %>
        <% end %>
      </div>
    </div>

    <div id="sign-in" class="make-payment col-md-6 col-md-offset-3">
      <div class="col-md-10 col-md-offset-1 text-center">
        Payment completed. Thank You
      </div>
    </div>

    <div class="grey col-md-4 col-md-offset-4 row text-center margin-top-20">
      <p> <%= link_to "Sign in", signin_path %></p>
    </div>
  </div>
</section>